version: "3.9"

services:
  postgresql:
    container_name: SatbayevOnlineStore
    image: postgres:14
    environment:
      POSTGRES_DB: "store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"